### ISSUE TITLE
Add welcome bot to this repo

### ISSUE THREAD

**Issue by malvikasharan** [ohbm/hackathon2020#132] opened 2020-06-05 13:15 UTC
## Summary

- Using behavior bot for welcome messages: https://github.com/apps/welcome

## What needs to be done:

- Using the behavior bot for your project would require configuring the master branch see here: https://github.com/apps/welcome
- I will create a config file for Welcome bot in the .github folder of this repo in a PR

## Who can help

- One admin or writer of this GitHub account will be able to do it

**Comment by Remi-Gau** [comment] 2020-06-05 13:18
Hey @malvikasharan 

Thank you a 10 0000 0000 00000 00000 times (as @cmaumet would say) for looking into this.

**Comment by Remi-Gau** [comment] 2020-06-05 13:22
I installed the bot for this repo.

So there is that.

**Comment by KirstieJane** [comment] 2020-06-05 13:26
Thanks @malvikasharan - tagging @Remi-Gau because he and I discussed this earlier today. Folks can see the welcome bot in action at the Turing Way repo:

* First issue: https://github.com/alan-turing-institute/the-turing-way/issues/1200#issuecomment-638940153
* First PR: https://github.com/alan-turing-institute/the-turing-way/pull/1194#issuecomment-637745394
* Merged PR: https://github.com/alan-turing-institute/the-turing-way/pull/1088#issuecomment-628553033

**Comment by KirstieJane** [comment] 2020-06-05 13:27
Oh lolz - I took so long finding those links the world moved on.

I told you I was now too old and mostly unhelpful 😆

**Comment by Remi-Gau** [comment] 2020-06-05 13:29
:laughing: 

I think the issue is more that I am **constantly** (too much) monitoring things transiting through this repo. So...

**Closed** 2020-06-07 15:54 UTC

**Comment by Remi-Gau** [comment] 2020-06-09 14:38
@malvikasharan you're gonna laugh

Apparently I must have messed up the set up of the bot on the Repo side because this ain't working.

:unamused: 

#IHadOneJobAndIMessedItUp

**Comment by malvikasharan** [comment] 2020-06-09 23:27
This has happened before. can I send some PR after investigating the config file? (they dislike some empty spaces in there.

**Comment by Remi-Gau** [comment] 2020-06-10 06:12
> This has happened before. can I send some PR after investigating the config file? (they dislike some empty spaces in there.

Of course you can. :smiley: 

But I was wondering if I forgot to do something when setting things up.

The [doc](https://github.com/apps/welcome) says:

```
Install the bot on the intended repositories. The plugin requires the following Permissions and Events:
- Pull requests: Read & Write
- Issues: Read & Write
```

And I have checked in several places but could not find where to set those permission levels.

**Comment by Remi-Gau** [comment] 2020-06-10 06:26
OK it seems that I have nothing to do to set those permissions AFAICT.

But there might be an indent problem on this [line](https://github.com/ohbm/hackathon2020/blob/6d0ce519b9c2d6eef8eddbd0ddec3b418ed631a2/.github/ISSUE_TEMPLATE/config.yml#L13)

Could that be it?
